---
- name: Play for Install Nginx on WebServers
  hosts: localhost
  connection: local
  become: true
  gather_facts: yes

  vars:
    custom_heading: "Welcome To Autoscaling Testing by Mohammed Rayees"

  tasks:
    - name: Update apt cache and install python3-apt
      apt:
        update_cache: yes
        name: python3-apt
        state: present

    - name: Install Nginx Server
      apt:
        name: nginx
        state: present

    - name: Copy the files to index destination folder
      template:
        src: /myrepo/index.j2
        dest: /var/www/html/index.nginx-debian.html
        owner: root
        group: root
        mode: '0644'

    - name: Copy the style files to destination folder
      copy:
        src: /myrepo/style.css
        dest: /var/www/html/style.css
        owner: root
        group: root
        mode: '0644'

    - name: Copy the javascript files to destination folder
      copy:
        src: /myrepo/scorekeeper.js
        dest: /var/www/html/scorekeeper.js
        owner: root
        group: root
        mode: '0644'

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
